### ISSUE TITLE
Get the interpolated value of a field at any position on the curve

### ISSUE THREAD

**Issue by jsepia** [bansheeGz/BGCurve#10]
I'm using BGCurve to make objects travel along a path. I added a custom field called `rotation` to my curve to define the desired rotation of each object at each point of the curve. I would like to be able to get the `rotation` value at any given position on the curve, even in between points.

Obviously this can't be done with all custom fields since not all field types are quantitative but at least it would be nice if this feature was available for those field types that can be interpolated (floats, vectors, etc).

I guess a prerequisite for this is the ability to get a point from a position on the curve (e.g. `GetNearestPointsByDistance()`). If developers could access points by their distance along the curve, or by their position in space, they could then access the custom fields associated with those points and interpolate them - or do whatever else they want. [The math classes already do this by running binary search on the points](https://github.com/bansheeGz/BGCurve/blob/27fce1dda9dc1c9e0909df69962eca9ef2cf76d6/Assets/BansheeGz/BGCurve/Scripts/Curve/BGCurveBaseMath.cs#L1237).

**Comment by banshee-gzzz** [comment]
Hi,

I agree currently there is no easy way to lerp different values between fields.

However, the code is there.
`BGCcCursorObjectRotate`  calculates quaternion value at any position on the curve according to the field value via `BGCcWithCursor.LerpQuaternion` function.
So you can get `rotation` value at any position on the curve (even between points).

Take a look at BGCcWithCursor.LerpQuaternion https://github.com/bansheeGz/BGCurve/blob/master/Assets/BansheeGz/BGCurve/Scripts/Cc/BGCcWithCursor.cs
It also has `GetT` method which calculates `t` value for `Quaternion.Lerp(@from, to, t)` method 

This `t` value can be used to lerp any value.

**Comment by banshee-gzzz** [comment]
This issue was addressed in the latest commits.
Cursor component now has methods for lerping fields values easily
