### ISSUE TITLE
Cursor won't move after spawn 2 or more cursor by script.

### ISSUE THREAD

**Issue by xertiniesz** [bansheeGz/BGCurve#13]
Hi BG,

I want to add cursor to math using script. The problem is if I added 2 or more cursor the cursor won't move, and it freeze at the starting point of the curve even I try to assign it position via DistanceRation.
What I have to do to make it work?. Thanks.

PS. Your asset is great!

My code.

```
// Use this for initialization
	void Start () {
        for (int i = 0; i < arrow; i++)
        {
            BGCcCursor cur = gameObject.AddComponent<BGCcCursor>();
            GameObject obj = Instantiate(movingObject, gameObject.transform.position, Quaternion.identity, gameObject.transform);
            BGCcCursorObjectTranslate objTran = gameObject.AddComponent<BGCcCursorObjectTranslate>();
            objTran.SetParent(cur);
            objTran.ObjectToManipulate = obj.transform;
            BGCcCursorObjectRotate objRot = gameObject.AddComponent<BGCcCursorObjectRotate>();
            objRot.SetParent(cur);
            objRot.ObjectToManipulate = obj.transform;
            objRot.OffsetAngle = new Vector3(0, -90, 0);
        }
        c = GameObject.Find("BGCurve").GetComponents<BGCcCursor>();
        Debug.Log(c.Length);
        for (int i = 0; i < c.Length; i++)
        {
            c[i].DistanceRatio = (0 + (1f / arrow) * i);
        }
    }
	
	// Update is called once per frame
	void Update () {
        if (level < 0) level = 0;
        if (level > 4) level = 4;

        for (int i = 0; i < c.Length; i++)
        {
            c[i].DistanceRatio += (float)(baseSpeed + (increament * level));
        }
        if (c[0].DistanceRatio >= 1/arrow)
        {
            for (int i = 0; i < c.Length; i++)
            {
                c[i].DistanceRatio = 0 + (1 / arrow) * i;
            }
        }
    }
```

**Comment by banshee-gzzz** [comment]
Hi, thank you for your support!

DistanceRatio works fine. If you rename Update method temporarily to something else, you will see that all objects are spawned in proper places.

The problem is a loss of fraction. 
Last lines in Update method should be 

        if (c[0].DistanceRatio >= 1f / arrow)
        {
            for (int i = 0; i < c.Length; i++)
            {
                c[i].DistanceRatio = 0 + (1f / arrow) * i;
            }
        }

You will need to use 1f instead of 1 (like you do above).
There are 2 places, you use 1 instead of 1f.
I hope it will help.

**Comment by xertiniesz** [comment]
YES!! It work now. Thank you. 

By the way.
What do you mean changing the update method name temporary? I'm very new to unity.

**Comment by banshee-gzzz** [comment]
I'm glad the issue is resolved
If you rename Update method to, say, Update2, Unity will not call it every frame, but Start method will be called (once). Since  you spawn your objects in Start method, you will see all objects with their starting positions
