### ISSUE TITLE
Text is almost invisible in BGCurve Custom and System Fields when using Unity Professional Skin

### ISSUE THREAD

**Issue by code-blep** [bansheeGz/BGCurve#15]
Hi, 

The field descriptions in the Custom and Editor Fields in BGCurve.cs , are almost invisible. This is due to the Unity Professional Skin using a light grey font.   

Thanks.

![git hub error](https://user-images.githubusercontent.com/8810407/62082210-36504680-b24c-11e9-9791-a18bc017b52e.PNG)

**Comment by banshee-gzzz** [comment]
This issue was fixed, thank you for reporting it

The latest package can be downloaded here: https://github.com/bansheeGz/BGCurve/tree/master/Package (v.1.2.7)
Or from Unity Asset Store in a couple of days (after review)
