### ISSUE TITLE
Incompatibility with Unity 2019.3.13f1+

### ISSUE THREAD

**Issue by JakeRabinowitz** [bansheeGz/BGCurve#18]
Hi, when I try to create a BGCurve using Unity `2019.3.13f1` or Unity `2019.4.0f1`, it doesn't display any of the point selection UI, or the overlay when holding ctrl.  It works when I use `2019.1.8f1`, so this might be related to the Unity UI refresh that happened as part of 2019.3?

Test Steps:
1. Install Unity 2019.3.13f1 or 2019.4.0.f1 using Unity Hub
1. Create a new project using Unity Hub.
1. Window > Asset Store > Import BGCurve.
1. In Hierarchy window: Right Click > Create Other > BansheeGZ > BG Curve.

Ctrl clicking / ctrl shift clicking doesn't work.  Manually adding points in the inspector doesn't show them.

Here's a screenshot showing side-by-side unity 2019.1 and 2019.4 with identical scenes & points.

![BGCurveIncompatibility](https://user-images.githubusercontent.com/1495255/84672520-7e686e00-aedd-11ea-9f99-fa6e43cf33c1.png)

Thanks!

**Comment by banshee-gzzz** [comment]
Hello, thank you for reporting the issue!
Unfortunately, I was not able to reproduce it, it works fine for me with both Unity 2019.3.13f1 and 2019.4.0.f1

Could you please check if "Show Curve" toggle is on under "Settings" tab as shown on the image below?
If it's on and you still do not see the curve- could you please send me your project so we could investigate this issue? 
Or alternatively, export your scene (Assets->Export package) with "Include dependencies" toggle on (please, see the screenshot below)
Thank you in advance
![Support_06_15_2020](https://user-images.githubusercontent.com/18222537/84687315-fb83f980-af56-11ea-99f3-5ae9fe163dd2.png)
![Support_06_15_2020_2](https://user-images.githubusercontent.com/18222537/84687322-fde65380-af56-11ea-81cc-66e47b1654b6.png)

**Comment by JakeRabinowitz** [comment]
Thanks for the quick reply!

The "Show Curve" toggle was on, so that's not the issue.

Here's the entire project: https://drive.google.com/file/d/1u7rSLeT703Lb2ESgeBgHGc-2PYdsM4Z8/view?usp=sharing
And just the scene: https://drive.google.com/file/d/1WooRWuLACArj7Oo1HBWO6Kw81tJAYuTt/view?usp=sharing

Thank you!

**Comment by banshee-gzzz** [comment]
Thank you for the project- it helped a lot!
We found the problem- "Gizmos" button was turned off so Editor's code, drawing the curve was not called
Turning this button on fixed the issue for me (please, see the screenshot below)

![Support_06_15_2020_3](https://user-images.githubusercontent.com/18222537/84800512-5f6df700-b017-11ea-97a8-ab4397dc119d.png)
.

**Comment by JakeRabinowitz** [comment]
Oh man 🤦 I should have noticed that. Thanks so much for your help!
