### ISSUE TITLE
Trigger Cursor Movement

### ISSUE THREAD

**Issue by woistjadefox** [bansheeGz/BGCurve#2]
Hi there! Thanks for these little master piece, the asset is pretty powerful! 

I'm actually going through the examples and the API / documentation. I'm wondering if it is already possible to trigger the cursor interpolation by script / UnityEvents? All the examples start with the animations right from the 1 frame.

**Comment by banshee-gzzz** [comment]
Hi! 
You can use BGCcCursorChangeLinear component (Cursor Change Linear) with speed set to 0.
Then change the speed when it's needed. 
Here is an example:

```
public class Test : MonoBehaviour {

    private BGCcCursorChangeLinear changeCursor;

	void Start ()
	{
	    changeCursor = GetComponent<BGCcCursorChangeLinear>();
	}
	
	void OnGUI ()
	{
	    if (GUILayout.Button("Go Back")) changeCursor.Speed = -1;
            else if (GUILayout.Button("Stop")) changeCursor.Speed = 0;
            else if (GUILayout.Button("Go Forward")) changeCursor.Speed = 1;

    }
}
```

**Comment by woistjadefox** [comment]
Ahh I see! Thanks for the hint. I just didn't realize that there are more components on the object, since only BGCurve is visible in the inspector. Interesting that you could hide components from the inspector view completely, didn't know that is possible. 

I've seen you are manipulating some vars via reflection for the inspector handling. Is this just in editor or also during run time?

**Comment by banshee-gzzz** [comment]
Mainly for the Editor, but some methods, related to Custom Fields handling and converting points between Inlined and GameObjects also use reflection in Runtime.
Do you have any concerns about reflection?

**Comment by woistjadefox** [comment]
Ok. I'm asking about reflection because the il2cpp scripting backend is AOT compiled and brings issues with certain reflection methods. (ios, webgl and some consoles make use of il2cpp in unity)

**Comment by banshee-gzzz** [comment]
Oh, I see, thanks for information. We'll do some tests on IOS and I will post results here. In case there will be any issue with them we'll  update the package.

**Comment by banshee-gzzz** [comment]
Update: we did some quick tests using WebGl, and it works just fine.
However, we decided to get rid of reflection at runtime completely, cause it was a bad idea to use it.
We will update the package soon (and we 'll test it on Webgl and Ios).
Thank you a lot for your feedback, if you have any other thoughts about improving the asset, please, let us know.

**Comment by banshee-gzzz** [comment]
No more Reflection dependancy at runtime since 1.2.1
Tested on IOS, Android, WebGl
