### ISSUE TITLE
point distance

### ISSUE THREAD

**Issue by vladthecodeimpaler** [bansheeGz/BGCurve#3]
Hello,
How can we calculate the distance for a given point?

did i miss something in the docs?

http://www.bansheegz.com/BGCurve/DeveloperGuide/Math/

Position and distance(optionally) for a point, which is on the spline and closest to some other point, which is not on the spline (math.CalcPositionByClosestPoint(Vector3 point))

**Comment by banshee-gzzz** [comment]
Hello,
Using this image as a reference (http://www.bansheegz.com/images/DGMathCalcPositionByClosestPoint.jpg)

If you need the length of the yellow arrow (we assume the green point is Vector3.zero)
```
        var math = GetComponent<BGCcMath>();
        //this is distance along the spline to the point, which lays on the spline and is closest to Vector3.zero (the length of yellow arrow)
	    float distanceYellow;
        //this is the position of this point (yellow circle)
	    var positionYellow = math.CalcPositionByClosestPoint(Vector3.zero, out distanceYellow);
```

If you need the length of the green arrow
```
        // (the length of green arrow)
	    var distanceGreen = Vector3.Distance(math.CalcPositionByClosestPoint(Vector3.zero), Vector3.zero);
```

We'll update the docs with examples soon.
Hope it helps

**Comment by vladthecodeimpaler** [comment]
Alright thanks
as a feature it would be nice if there is a method on every point, like so point.GetDistance

**Comment by banshee-gzzz** [comment]
thank you for your suggestion, we'll add such method to the next version.
But we can not add it to points, cause to know the distance we need Math, but nor curve nor points know nothing about math. Besides "math" can use different methods to approximate the spline, so there is no any "standard" approximation.

Currently you can use the following code to get the distance to a point (0-zero point, 1- first point)
```
        var math = GetComponent<BGCcMath>();
	    var distanceToFirstPoint =  math.Math[1].DistanceFromStartToOrigin;
        //or
        var distanceToFirstPointAlternative = math.Math[0].DistanceFromEndToOrigin;
```
Hope it helps
