### ISSUE TITLE
Large distance between points and delay bug?

### ISSUE THREAD

**Issue by kokosnoot2k** [bansheeGz/BGCurve#5]
Hi,

Currently I am trying to use BGCurve to make an animation. All is going well, except I have one issue where the cursor gets stuck. Maybe it's a precision issue, I don't know.

So I have been trying to figure out if something is a bug or not, and I think it is. I am currently using 1.2.2, but also just installed 1.2.3 Beta as a test. The problem still persists.

The problem is that the Lerp component gets "stuck" on a point when there are delays and large distances involved.

**A quick test case**:

- [ ] Create an BGCurve that moves an object around (So, component: Math, Cursor, Cursor Change Linear and Translate object by cursor).
- [ ] Add a custom field called "delay" (type: float)
- [ ] Specify that this "delay" field is used as a delay field in "Cursor Change Linear".
- [ ] Overflow control: stop.
- [ ] Speed 5

Add 4 points as below, type "Absent". I  normally use symmetric independent, but for the example it does not matter.
**x y z**
-16.50 0 0
-97.70 0 -12.00
20.00 0 0
11.00 0 10.90

Give point 2 and 3 a delay of 5 seconds.

Run! :-) - The object will correctly manage to get to the last point (index: 3)

Now Stop the Unity project.

Now multiply all values with 100:

**x y z**
-1650 0 0
-9770 0 -1200
2000 0 0
1100 0 1090
Speed also 500 (but the value does not matter, lower is fine too if you have more patience)

Run again. 
Now the object will get stuck **after point 2** and jump back and forth a tiny bit. Removing the delay while running will immediately make it continue again.

Any ideas what can cause this problem? I suppose it's a precision issue maybe, but I have been unable to pinpoint the exact location of this issue.

**Comment by banshee-gzzz** [comment]
Yes, this can certainly be a bug related to precision.
Give us some time to check it out

**Comment by banshee-gzzz** [comment]
I confirm, there is a precision related bug with Lerp component
we provided a fix, mitigating this issue https://github.com/bansheeGz/BGCurve/blob/master/Package/BGCurve1.2.3.beta.unitypackage

It removes an issue with the data you provided, however I'm not sure it wont reappear under more extreme conditions. 
Hopefully it'll help.
