### ISSUE TITLE
Manipulate multiple objects

### ISSUE THREAD

**Issue by JSBmanD** [bansheeGz/BGCurve#6]
Hello.
I've created math with cursor, translate, ccl. If I wouldn't set translate object directly there will be an error(not critical). But I have attached object by code. I think that is a bug.

**Comment by banshee-gzzz** [comment]
I just tried setting an object by code, and it's translated properly.
Could you provide more details about the bug?

**Comment by JSBmanD** [comment]
I mean just visual warning. Yes, it's translating properly but in this module there's alert.

**Comment by banshee-gzzz** [comment]
it's meant to work this way.
So people would know, the component will not work until they assign a required field.
If you assign it by code, you can simply ignore it, cause it does not affect anything
