### ISSUE TITLE
Dragging an object attached to a cursor

### ISSUE THREAD

**Issue by PavulonTwist** [bansheeGz/BGCurve#9]
Hi, I'm trying to implement mouse dragging of an object along spline.
For simple splines I could use `Math.getPositionByClosestPoint`, but that wouldn't work for spline crossing itself or for spiral cases.
My idea was to simply move cursor by a distance using a dot product between cursor's tangent and a vector from cursor to mouse position:
```
private void HandleDragging() {
	Vector3 cursorPosition;
	Vector3 tangent;
	cursorPosition = cursor.Math.CalcPositionAndTangentByDistance(cursor.Distance, out tangent);
	Vector3 mousePositionWorld = Camera.main.ScreenToWorldPoint(Input.mousePosition);
	mousePositionWorld.z = 0.0f; // It's 2D, so I don't care about Z axis
	cursorPosition.z = 0.0f;
	float dot = Vector3.Dot(tangent, mousePositionWorld - cursorPosition);
	float distanceDelta = Time.deltaTime * Mathf.Min(dot * speedMultiplier, maxSpeed);
	cursor.Distance += distanceDelta;
}
```
That works quite well, but it has quite serious flaw - when your spline has an arc and you drag quite far away from the convex side of the arc then your dragged object will start to jump around the point where it should be actually projected. This is caused by the fact that when mouse position is far away from cursor then small changes in the tangent along spline results in big distances when projecting with dot product.
I've tried to fix it by reducing the magnitude of vector from cursor to mouse position and it works, but it introduces visible slow-down in cursor movement when dragging fast.
I can see several solutions:
1. Manualy calculate closest point on the spline by doing multiple iterations which moves closer and closer to the minimum distance (I assume that one could affect performance).
2. Additional parameter for `Math.getPositionByClosestPoint` that could limit a range on which it searches for the closest point
3. Additional function for Cursor to handle such dragging.

Could you help me out?
Maybe I missed out something in the current API and that could be implemented easier?
Maybe the approach could be changed to implement it with current API?
Or maybe you would find it worth to provide my suggestions from points 2 or 3 in next release?

**Comment by banshee-gzzz** [comment]
Hi, no, we don't plan to add any new components or change API at the moment.
Regarding the object jumping around the point- could you try to add some angular threshold, so if it's around 90 (270) degrees, the object would stop? 
Something like 

```
var toMouse = mousePositionWorld - cursorPosition;
float dot = Vector3.Dot(tangent, toMouse.normalized);
if(dot<AngularThreshold){//do nothing, object is stopped}
else {//change cursor here}
```

will it work for you?

**Comment by PavulonTwist** [comment]
I'm not sure how angular threshold corresponds to the dot product AKA magnitude of vector of toMouse vector projected to tangent (normalized) vector.
Disregarding the fact that dot product has nothing to do with angle, the solution you suggested with a threshold doesn't fix the problem - it just stops cursor when the distance is too long. That even makes the problem worse as it additionally breaks cases when the user would move the object faster than the threshold lets you.
I've tried a couple of workarounds and improvements to that solution, but I've ended up in banging my head against a wall with a conclusion that different approach is needed.
If you don't plan any API changes I think I'll just implement point 2 myself as it seems to be stable, fast and easy enough.

> we don't plan to add any new components or change API at the moment.

Does it mean that BGCurve won't be developed anymore? What are the plans for the project then? What should I do when I implement point 2 - Should I start new branch of this project?

**Comment by banshee-gzzz** [comment]
As far as I understand, your issue is that your object does not stop at the projected point, but rather start jumping around it if the mouse cursor is far enough.
So I thought, you can calculate the angle between 2 vectors and if it's around 90 degrees, you simply stop the cursor, cause you can not decide, should you move it forward or backward, no matter how far the mouse cursor is.
Dot product is magnitudes of 2 vectors multiplied by the cosine of the angle between them.
So, in the example above, if you take dot product of 2 normalized vectors (tangent and toMouse are normalized), it should be around zero for angle around 90 degrees no matter how far the mouse cursor is (the condition has an error though, it should be if(Math.Abs(dot)<AngularThreshold)). You can use Vector2.Angle instead of dot as well.

So, it should stop the object as soon as this angle is around 90 degrees and it looks like it's much easier solution than any other option you mentioned. Or (it's also possible) that I do not understand what your task and issue really are.

At the moment, we do not plan to develop it further for many reasons, except bugs fixing, but if you want to merge your own changes for Math.getPositionByClosestPoint method, we'd appreciate it. Simply fork it and create a pull request.

**Comment by PavulonTwist** [comment]
Ah, now I understood your solution - ignoring of projections of almost perpendicular vectors which anyway result in small distances in projection.
In your description you used 2 normalized vectors. I wanted only tangent to be normalized to project on it full length of mousePos vector. When both vectors are normalized the issue is gone, but it introduces a lag when fast dragging (as I've desribed in my first comment).
Solution with only tangent normalized and ignoring projections of almost perpendicular vectors doesn't help as on sharp arcs the tangent changes it's angle quickly and for large distances to mouse it will make the projection technique useless as it will overshoot target (as we project on straight line and try to apply such distance on arc).
Nevertheless, that gave me an idea how to workaround that problem by mixing the check of almost perpendicular vectors with normalization of both vectors:
```
private void HandleDragging() {
  Vector3 tangent;
  Vector2 cursorPosition = cursor.Math.CalcPositionAndTangentByDistance(cursor.Distance, out tangent);
  Vector2 mousePositionWorld = Camera.main.ScreenToWorldPoint(Input.mousePosition);
  Vector2 mouseDir = (mousePositionWorld - cursorPosition);
  if (mouseDir.sqrMagnitude > 1.0f && Mathf.Abs(Vector2.Angle(tangent, mouseDir)) > 45.0f) {
    mouseDir.Normalize();
  }
  float dot = Vector3.Dot(tangent, mouseDir);
  float distanceDelta = Time.deltaTime * Mathf.Min(dot * speedMultiplier, maxSpeed);
  cursor.Distance += distanceDelta;
}
```
This solution improves the situation when the arcs are smooth enough, but with very sharp arcs it still doesn't work, so I believe this approach cannot be used for general case and more sophisticated approach is needed. Anyway that could suffice for now. If better approach will be needed I will implement point 2 and I'll let you know with pull request about that :)
Thanks, for support!

**Comment by banshee-gzzz** [comment]
ok, I'm glad you found a solution
